create table Author
(
    id      int generated by default as identity primary key,
    name    varchar not null,
    surname varchar,
    country varchar
);

create table Book
(
    id        int generated by default as identity primary key,
    author_id int references Author (id) ON DELETE CASCADE,
    genre_id  int     references Genre (id) ON DELETE SET NULL,
    title     varchar not null,
    series    varchar
);

create table Genre
(
    id         int generated by default as identity primary key,
    is_fiction bool,
    name       varchar
);

create table Recommendation
(
    book_id   int references Book (id),
    author_id int references Author (id),
    primary key (book_id, author_id)
);

create table "User"
(
    id       int generated by default as identity primary key,
    login    varchar(10) not null,
    password varchar(10) not null,
    is_admin boolean     not null
);

create table UserBook
(
    book_id     int references Book (id),
    user_id     int references "User" (id),
    primary key (book_id, user_id),

    is_read     bool,
    is_demanded bool
);

create table Quote
(
    id       int generated by default as identity primary key,
    book_id  int references Book (id),
    page     int     not null,
    contents varchar not null
);

create table BookReview
(
    id       int primary key references Book (id),
    user_id  int references "User" (id),
    book_id  int references Book (id),
    rating   int     not null,
    contents varchar not null
);

create table BookIssue
(
    id           int generated by default as identity primary key,
    book_id      int references Book (id),
    publisher_id int references Publisher (id),

    year         int,
    quantity     int,
    price        double precision
);

create table Publisher
(
    id      int generated by default as identity primary key,
    name    varchar,
    address varchar,
    phone   varchar
);