drop table if exists Publisher;
drop table if exists BookIssue;
drop table if exists BookReview;
drop table if exists Quote;
drop table if exists UserBook;
drop table if exists "User";
drop table if exists Recommendation;
drop table if exists Book;
drop table if exists Genre;
drop table if exists Author;

create table Author
(
    id      int generated by default as identity primary key,
    name    varchar NOT NULL,
    surname varchar,
    country varchar
);

insert into Author(name, surname, country)
values ('Фёдор', 'Достоевский', 'Россия');
insert into Author(name, surname, country)
values ('Лев', 'Толстой', 'Россия');
insert into Author(name, surname, country)
values ('Михаил', 'Булгаков', 'СССР');
insert into Author(name, surname, country)
values ('Михаил', 'Шолохов', 'СССР');
insert into Author(name, surname, country)
values ('Стивен', 'Кинг', 'США');
insert into Author(name, surname, country)
values ('Айзек', 'Азимов', 'США');
insert into Author(name, surname, country)
values ('Нассим Николас', 'Талеб', 'США');
insert into Author(name, surname, country)
values ('Агата', 'Кристи', 'Великобритания');
insert into Author(name, surname, country)
values ('Артур Конан', 'Дойл', 'Великобритания');
insert into Author(name, surname, country)
values ('Станислав', 'Лем', 'Польша');
insert into Author(name, surname, country)
values ('Генрик', 'Сенкевич', 'Польша');
insert into Author(name, surname, country)
values ('Болеслав', 'Прус', 'Польша');
insert into Author(name, surname, country)
values ('Александр', 'Дюма', 'Франция');
insert into Author(name, surname, country)
values ('Мишель', 'Фуко', 'Франция');
insert into Author(name, surname, country)
values ('Марсель', 'Пруст', 'Франция');

create table Genre
(
    id         int generated by default as identity primary key,
    name       varchar,
    is_fiction bool DEFAULT true
);

insert into Genre(name)
values ('Фантастика');
insert into Genre(name)
values ('Исторический роман');
insert into Genre(name)
values ('Психологический роман');
insert into Genre(name)
values ('Фэнтэзи');
insert into Genre(name)
values ('Детектив');
insert into Genre(name, is_fiction)
values ('Философия', false);
insert into Genre(name, is_fiction)
values ('Экономика', false);
insert into Genre(name)
values ('Ужасы');
insert into Genre(name)
values ('Приключения');

create table Book
(
    id        int generated by default as identity primary key,
    author_id int references Author (id) ON DELETE CASCADE,
    genre_id  int     references Genre (id) ON DELETE SET NULL,
    title     varchar not null,
    series    varchar
);

INSERT INTO Book (author_id, title, series, genre_id)
VALUES (1, 'Преступление и наказание', 'Романы Достоевского', 3);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (1, 'Братья Карамазовы', 'Романы Достоевского', 3);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (2, 'Война и мир', 'Романы Толстого', 2);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (2, 'Анна Каренина', 'Романы Толстого', 3);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (3, 'Мастер и Маргарита', NULL, 4);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (4, 'Тихий Дон', NULL, 2);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (5, 'Оно', 'Цикл "Оно"', 8);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (6, 'Я, робот', NULL, 1);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (7, 'Чёрный лебедь', NULL, 7);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (8, 'Убийство в Восточном экспрессе', 'Эркюль Пуаро', 5);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (9, 'Приключения Шерлока Холмса', 'Шерлок Холмс', 5);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (10, 'Солярис', NULL, 1);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (11, 'Камо грядеши', NULL, 2);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (12, 'Фараон', NULL, 2);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (13, 'Граф Монте-Кристо', NULL, 2);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (14, 'Надзирать и наказывать', NULL, 6);
INSERT INTO Book (author_id, title, series, genre_id)
VALUES (15, 'В поисках утраченного времени', 'В поисках утраченного времени', 3);

create table Recommendation
(
    book_id   int references Book (id) ON DELETE CASCADE,
    author_id int references Author (id) ON DELETE CASCADE,
    primary key (book_id, author_id)
);

INSERT INTO Recommendation (book_id, author_id)
VALUES (1, 2);
INSERT INTO Recommendation (book_id, author_id)
VALUES (4, 5);
INSERT INTO Recommendation (book_id, author_id)
VALUES (1, 4);
INSERT INTO Recommendation (book_id, author_id)
VALUES (3, 7);

create table "User"
(
    id       int generated by default as identity primary key,
    login    varchar(10) not null,
    password varchar(10) not null,
    is_admin boolean     not null default false
);

INSERT INTO "User" (login, password, is_admin)
values ('victor', 'victor', true);
INSERT INTO "User" (login, password)
values ('pliska', 'pliska');

create table UserBook
(
    book_id     int references Book (id) ON DELETE CASCADE,
    user_id     int references "User" (id) ON DELETE CASCADE,
    primary key (book_id, user_id),

    is_read     bool default false,
    is_demanded bool default false
);

create table Quote
(
    id       int generated by default as identity primary key,
    book_id  int references Book (id),
    page     int     not null,
    contents varchar not null
);

create table BookReview
(
    id       int primary key references Book (id),
    user_id  int references "User" (id),
    book_id  int references Book (id),
    rating   int          not null,
    contents varchar(100) not null
);

create table Publisher
(
    id      int generated by default as identity primary key,
    name    varchar(30) not null,
    address varchar     not null,
    phone   varchar
);

create table BookIssue
(
    id           int generated by default as identity primary key,
    book_id      int references Book (id),
    publisher_id int references Publisher (id),

    year         int not null,
    quantity     int not null,
    price        double precision
);